---
title: "Syllabus"
format:
    html: default
    pdf: default
---

# BTS 510 Syllabus -- Fall 2026

## Instructor information

* Stefany Coxe, Ph.D.  
    * [stefany.coxe@csmc.edu](mailto:stefany.coxe@csmc.edu)  
    * Office hours: By appointment (send me an email to schedule)
* Yujie Cui, M.S.
    * [yujie.cui@cshs.org](mailto:yujie.cui@cshs.org)
    * Office hours: TBD

## Course information

### Learning goals

This course covers *linear models* (i.e., regression) with an emphasis on **experimental studies**. Topics include using and manipulating datasets, plotting data, estimation and uncertainty, linear regression, logistic regression, Poisson regression, and survival analysis.

#### Learning objectives

* **Select** the appropriate linear model for the research question
* **Analyze** data with the appropriate linear model
* **Describe** your findings for scientific and non-scientific audiences
* **Create** a written report of your findings
* **Make conclusions** about your research question(s) based on those results

### Course structure 

#### Time and location

We will meet in-person on **Thursday** from *10am to 11:30am* in **BTS classroom on the 7th floor of PDC**.

#### Course format

This course takes place in a **[flipped](https://en.wikipedia.org/wiki/Flipped_classroom), hybrid format**. We will meet in person for 1 hour 30 minutes each week. This time will be spent on **hands-on statistical programming in R**. You will be responsible for completing course assignments such as videos and readings **prior to class** in order to be prepared to participate in the in-person meeting. You will also have assignments to complete after class.

Each week will follow a similar structure:

* Monday: Lecture videos posted
* Wednesday: Watch lecture and respond to survey by 8pm Wednesday
* Thursday: In-person meeting to review material and work on applications
* Sunday: Homework assignment due by end of day (midnight)

### Software

We will be using **R** for this course. It's ok if you don't know how to use R (but also great if you do!). We'll start from scratch in the first few weeks. I will provide information about the specific procedures you will need to know for this course.

* R is free and open source and works on any platform (Windows, Mac, Unix)
    * Download R [here](https://cran.r-project.org/)
    * I also recommend using Rstudio, which can be downloaded [here](https://posit.co/download/rstudio-desktop/)
    * If you use a Chromebook or tablet, you can use [Rstudio via the cloud](https://posit.cloud/)
        * I have not used this much, so I don't know all its shortcomings
* We'll also be using [Quarto](https://quarto.org/)
    * Publishing system based on markdown
    * Intersperse plain text and code
    * Output to convenient formats, like HTML, PDF, Word
    * [Install Quarto](https://quarto.org/docs/get-started/)

### Assessments

Your work in this course will be assessed using a variety of methods.

#### Lecture videos (10%)

Watch the lecture video. Respond to the survey afterward with questions and comments.

#### Homework (60%)

There will be **five (5)** homework assignments. The assignments generally involve running analyses in R, interpreting output, and presenting the results.

#### Final project (30%)

You will select a dataset, propose some research questions that can be answered using linear models, write up the results, and present your findings to the class. More details to follow throughout the semester.

* Dataset selection: 5% of project grade
* Proposal: 15% of project grade
* Presentation: 40% of project grade
* Final paper: 40% of project grade

### Tentative schedule

Week	  | Date          |	Topic	                        |	L	    |	H	    |
|:------|:--------------|:------------------------------|:------|:------|
1	    |	Sept 03    	|	Introduction, R, markdown	        |	1	    |		|
2	    |	Sept 10	    |	Data manipulation	                |	2	    |	1	|
3	    |	Sept 17     |	Samples, sampling distribution	  |	3	    |	 	|
4	    |	Sept 24 	  |	ggplot  	                        |	4	    |	Data	|
5	    |	Oct 01 	    |	ggplot	                          |	5	    |	2	|
6	    |	Oct 08	    |	Linear regression	                |	6	    |	  |
7	    |	Oct 15	    |	Linear regression                 |	7	    |	3	|
8	    |	Oct 22	    |	Linear regression         	      |	8	    |	 	|
9	    |	Oct 29  	  |	Linear regression    	            |	9	    |	Proposal	|
10	  |	Nov 05	    |	Linear regression	                |	10    |	4	|
11	  |	Nov 12	    |	Logistic regression               |	11    |		|
12	  |	Nov 19	    |	Poisson regression   	            |	12	  |	5 |
13	  |	Nov 26	    |	NO CLASS              	          |	  	  |		|
14	  |	Dec 03      |	Survival analysis                 |	13	  |		|
15	  |	Dec 10    	|	Repeated measures                 |	14	  |	 	|
16	  |	Dec 17  	  |	Presentations	                    |		    | Final	| 

- **L**: Watch lecture videos and respond to survey by **Wednesday at 8pm**.
- **H**: Homework assignments are due by the **end of Sunday (midnight)**.
- **Final project**  
  - **Data**: Description of data due by September 27 
  - **Proposal**: Proposal of final project due by November 1  
  - **Presentation**: Presentation in class on December 17  
  - **Paper**: Final paper due by December 20  
- **All due dates subject to change** due to weather, emergency, scheduling changes, etc.

### Grades

| Grade | Percentage |
|:------|:-----------|
| A+    | \>=97      |
| A     | 93 - 96.99 |
| A-    | 90 - 92.99 |
| B+    | 87 - 89.99 |
| B     | 83 - 86.99 |
| B-    | 80 - 82.99 |
| C+    | 77 - 79.99 |
| C     | 70 - 76.99 |
| D+    | 65 - 69.99 |
| D     | 60 - 64.99 |
| F     | \<= 59.99  |

## Cedars-Sinai policies

### Attendance

Attendance is not explicitly part of your grade in this course, but activities completed during the in-person portion of the course will be **very** helpful. If you need to miss class (such as for illness, religious event, professional activity, university-sanctioned event, or **any other reason**), please contact me to make any necessary arrangements.

### Academic dishonesty and misconduct

Please refer to your [policy handbook](https://www.cedars-sinai.edu/content/dam/cedars-sinai/education/documents/graduate-research-education/graduate-school-of-biomedical-sciences-handbook.pdf) for a description of what constitutes academic dishonesty. 

* **While you may work with other students on your homework assignments, I expect all students to complete and turn in their own work.**
